postgresql:
  auth:
    existingSecret: postgresql-secret
    username: zabbix
    database: zabbix
  primary:
    nodeSelector:
      "kubernetes.io/hostname": minikube
#    persistence:
#      enabled: true
#      storageClass: postgresql-storage-class
#      existingClaim: postgresql-pvc
#      accessModes: ReadWriteOnce
#      size: 8Gi


