postgresql:
  auth:
    existingSecret: postgresql-secret
    username: zabbix
    database: zabbix
  primary:
    nodeSelector:
      "kubernetes.io/hostname": tunmonit
    persistence:
      enabled: true
      storageClass: postgresql-storage-class
      existingClaim: postgresql-pvc
      accessModes: ["ReadWriteOnce"]
      size: 8Gi
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - minikube
                    - tunmonit


