kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  local:
    path: /kubernetes-persistent-volume/postgresql
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: {{ .Release.Namespace }}
     name: {{ .Values.postgresql.persistence.existingClaim }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube